<a href="https://colab.research.google.com/github/miguel1319/PyTorch-Learn/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This is the begining of the PyTorch lesson
--Focusing on Neural tework and Deep Learning


In [ ]:
import torch
import numpy as np
#!pip list
#https://pytorch.org/docs/stable/index.html

In [ ]:
print("lets add this to Git Hub")

lets add this ti Git Hub


#Tensors
Similar to a n-dimensional matrix <br>
lists < numpyarray < tensor <br>
review to start with torch regarding reshape, slice, arithmetic operations.

In [ ]:
my_arr = [[7,6,5],[4,5,7]]
np1 = np.random.rand(2,3)
print(np1,np1.dtype,"\n")
tensor1 = torch.zeros(3,4,7)
print(tensor1,tensor1.dtype,"\n")


[[0.98916716 0.71527171 0.77899185]
 [0.94611903 0.24972971 0.30953592]] float64 

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]]) torch.float32 

cpu


In [ ]:
print(torch.tensor(np1))
print("\n",tensor1.device)

tensor([[0.9892, 0.7153, 0.7790],
        [0.9461, 0.2497, 0.3095]], dtype=torch.float64)

 cpu


In [ ]:
#reshape
my_torch = torch.arange(10)
print(my_torch,"\n")
my_torch = my_torch.reshape(5,2) # 10 has prime factors 2,5
print(my_torch,"\n")
my_torch = my_torch.reshape(-1,2)# when not knowing exaclty how to divide
print(my_torch,"\n")
my_torch = my_torch.reshape(-1,2)
print(my_torch,"\n")

#slices
my_torch = torch.arange(10)
print(my_torch[7],"\n")
my_torch = my_torch.reshape(5,2)# reshaping to a 2d matrix
print(my_torch[:,1],"\n")#gets items without shape
print(my_torch[:,1:],"\n")#maintain shape


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]) 

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]) 

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]) 

tensor(7) 

tensor([1, 3, 5, 7, 9]) 

tensor([[1],
        [3],
        [5],
        [7],
        [9]]) 



In [ ]:
#math operations
tensor_a = torch.tensor([0,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

tensor_a + tensor_b
torch.add(tensor_a, tensor_b)
tensor_a * 9
torch.pow(tensor_a,1)

tensor([0, 2, 3, 4])

In [ ]:
tensor_a.add(tensor_a)
print(tensor_a)
tensor_a.add_(tensor_a)
print(tensor_a)

tensor([0, 2, 3, 4])
tensor([0, 4, 6, 8])


###Starting a Neural Network
Input  Hiiden  Output


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
#Create a Model that inherits nn.Module
class Model(nn.Module):
  #input layer (4 features)
  def __init__(self,in_features=4,h1=8,h2=9,out_features = 3):
    super().__init__() #instanciate out nn.Model
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x=F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x




In [ ]:
#pick random seed
torch.manual_seed(41)
#create instance of a model
model = Model()
